### PR TITLE
3.x

### PR DESCRIPTION
**Pull request by ddt3**
- Corrected layout errors (wiki -> rst)
- Added Perlstone description
- Added some missing descriptions
- Added ProtocolLib explanation

### CODE REVIEW

**Comment by me4502** [comment]
Thanks, looks good :)

However, I think this PR includes some commits that have already been merged from previous PRs? Those would need to be removed before I can merge

**Comment by ddt3** [comment]
I have not been able to remove the commits that had already been included, so abandoning this one to see if I can create a new PR with only the commit needed

**Comment by me4502** [comment]
I've manually pulled the change across

**Comment by ddt3** [comment]
I will remove my fork and start from scratch for my next contribution ;-)

**Pull request closed without merging**
