### PR TITLE
Updates permission for using chairs

### PR DESCRIPTION
**Pull request by R1yuu**
The before mentioned permission was wrong. I looked in the Sourcecode and found the right one

### CODE REVIEW

**Comment by wizjany** [comment]
This is targeting the master branch, which is the 4.x (Sponge) documentation. Are you sure you're not using 3.x (i.e. bukkit/spigot)?

**Comment by R1yuu** [comment]
https://craftbook.enginehub.org/en/latest/mechanics/chairs/

It's wrong on the latest version as far as im aware

**Comment by wizjany** [comment]
That's the point. 3.x isn't the "latest". https://craftbook.enginehub.org/en/3.x/

**Comment by R1yuu** [comment]
Okay i see my error. Nvm me then.

**Pull request closed without merging**
