### PR TITLE
3.x

### PR DESCRIPTION
**Pull request by ddt3**
Added more info from the old wiki to the current documentation

### CODE REVIEW

**Comment by me4502** [comment]
Thanks, would it be possible to move the search area docs outside of the ICs folder?

**Comment by ddt3** [comment]
Out of the ICs folder, into the mechanics folder? Sure. Done

**Comment by me4502** [comment]
Sorry I meant into the root folder, like item_syntax

**Comment by ddt3** [comment]
I moved it, although I am not sure why, it is only used in IC.
as a bonus I added player_type too

**Review by me4502 — APPROVED** [review]

**Comment by me4502** [comment]
Thanks

**Pull request merged**
